AGENT_PORT = 8333
AGENT_CLEAN_INTERVAL = 5

CLUSTER_SYNC_CURRENT_DIR = True
CLUSTER_SCHEDULE_INTERVAL = 0.1

PLATFORM_PAAS_VM_WAIT_INTERVAL = 1
PLATFORM_PAAS_SSH_RETRIES = 10
PLATFORM_PAAS_SSH_RETRY_INTERVAL = 1

PLATFORM_EC2_REGION = "ap-southeast-1"
PLATFORM_EC2_VM_TAG = "mrkt"

SERVICE_CONTAINER_PREFIX = "mrkt"

SERVICE_IMAGE_ARCHIVE = None
SERVICE_IMAGE_UPDATE = False
SERVICE_IMAGE_CLEAN = False

SERVICE_DOCKER_IMAGE = "tefx/mrkt"

SERVICE_SSH_RETRY_TIMES = 2
SERVICE_SSH_RETRY_INTERVAL = 1

TASK_WAIT_PID_RETRIES = 5
TASK_WAIT_PID_RETRY_INTERVAL = 0.5

TOOL_CMD_PIP = "pip"

RDIFF_SIG_FILENAME = ".sig"
RDIFF_DELTA_FILENAME = ".delta"

PORT_CONNECT_RETRIES = 10
PORT_CONNECT_RETRY_INTERVAL = 1
