AGENT_PORT = 8333
AGENT_CLEAN_PROCESS_INTERVAL = 5

CLUSTER_SYNC_CURRENT_DIR_DEFAULT = True
CLUSTER_SCHEDULE_INTERVAL = 0.1

PLATFORM_EC2_USERNAME_DEFAULT= "core"
PLATFORM_EC2_REGION_DEFAULT = "ap-southeast-1"
PLATFORM_EC2_URL_AMI_COREOS = "https://stable.release.core-os.net/amd64-usr/current/coreos_production_ami_hvm_{region}.txt"
PLATFORM_EC2_INSTANCE_TAG= "mrkt"
PLATFORM_EC2_INSTANCE_READY_WAIT_INTERVAL = 1
PLATFORM_EC2_SSH_RETRY_TIMES = 10
PLATFROM_EC2_SSH_RETRY_INTERVAL = 1

SERVICE_CONTAINER_IMAGE_DEFAULT = "tefx/mrkt"
SERVICE_CONTAINER_IMAGE_ARCHIVE_DEFAULT = None
SERVICE_CONTAINER_IMAGE_UPDATE_DEFAULT = False
SERVICE_CONTAINER_IMAGE_CLEAN_DEFAULT = False
SERVICE_CONTAINER_NAME_PREFIX = "mrkt"
SERVICE_SSH_RETRY_TIMES = 2
SERVICE_SSH_RETRY_INTERVAL = 1

TASK_WAIT_PID_RETRY_TIMES = 5
TASK_WAIT_PID_RETRY_INTERVAL = 0.5

TOOL_CMD_PIP = "pip"

RDIFF_FILE_SIG = ".sig"
RDIFF_FILE_DELTA = ".delta"

PORT_CONNECT_RETRY_TIMES = 10
PORT_CONNECT_RETRY_INTERVAL = 1
